# Generated by Django 4.1.6 on 2023-04-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=400)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
