# Generated by Django 4.1.6 on 2023-04-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='TodoModel',
        ),
    ]
