# Generated by Django 4.1.6 on 2023-04-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_todo_todomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='task',
            new_name='task_name',
        ),
    ]
